name: Ruby

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7.8'
          - '3.0.7'
          - '3.1.6'
          - '3.2.5'
          - '3.3.4'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Lint
      run: bundle exec rubocop
    - name: Test
      run: bundle exec rspec
